# Generated by Django 3.2.6 on 2021-08-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petId', models.CharField(max_length=32, unique=True)),
                ('nome_pet', models.CharField(max_length=50)),
                ('dono', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('nascimento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.pet')),
            ],
        ),
    ]
