# Generated by Django 3.2.6 on 2021-08-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petId', models.CharField(max_length=32, unique=True)),
                ('nome_pet', models.CharField(max_length=50)),
                ('dono', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
