# Generated by Django 3.2.6 on 2021-08-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='data_nascimento',
            new_name='datanascimento',
        ),
    ]
