# Generated by Django 3.2.6 on 2021-08-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0004_rename_data_nascimento_pet_datanascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='datanascimento',
            new_name='nascimento',
        ),
    ]
